#!/bin/env python3

# Created by: Trent Hodgins
# Created on: 10/11/2021
# This program is the Space Aliens Game program on the PyBadge

import ugame
import stage


def game_scene():
    # this function is the main game game_screen
    
    image_bank_background = stage.Bank.from_bmp16("space_aliens_background.bmp")
    image_bank_sprites = stage.Bank.from_bmp16("space_aliens.bmp")
    background = stage.Grid(image_bank_background, 10, 8)
    
    ship = stage.Sprite(image_bank_sprites, 5, 75, 66)
    
    game = stage.Stage(ugame.display, 60)
    game.layers = [ship] + [background]
    game.render_block()
    
    while True:
        # get user input
        
        # update game logic
        
        # redraw Sprites
        game.render_sprites([ship])
        game.tick()
    
if __name__ == "__main__":
    game_scene()
