#!/bin/env python3

# Created by: Trent Hodgins
# Created on: 10/07/2021
# This program is the Space Aliens Game program on the PyBadge

import ugame
import stage


def game_scene():
    # this function is the main game game_screen
    
    image_bank_background = stage.Bank.from_bmp16("space_aliens_background.bmp")
    background = stage.Grid(image_bank_background, 10, 8)
    
    game = stage.Stage(ugame.display, 60)
    game.layers = [background]
    game.render_block()
    
    while True:
        # repeat forever, game Loop
        pass # just a placeholder for now
    
if __name__ == "__main__":
    game_scene()
